// Núcleo de campaña: Director/Jugador, sesión cero, herramientas y sistemas persistentes.
const fs=require('fs'),path=require('path');
const {makeApp,makeSeed,reporter,P}=require('./harness');
const fw={};new Function('window',fs.readFileSync(path.join(P,'rpg-engine.js'),'utf8'))(fw);const E=fw.LoreRpgEngine;
const R=reporter('campaign-systems'),ok=R.ok;
const world={title:'Mundo',projectMode:'rpg',rpg:{role:'player',player:E.defaultPlayer()}};E.ensureStory(world);
ok('migración crea 8 sistemas y relaciones', ['factions','quests','inventory','wounds','clues','clocks','locations','rumors'].every(k=>Array.isArray(world.rpg.worldState[k]))&&typeof world.rpg.worldState.relationships==='object');
let out=E.executeCampaignCommand(world,'/estado');
ok('/estado funciona para jugador sin IA',out.handled&&out.ok&&/Mundo:/.test(out.message));
out=E.executeCampaignCommand(world,'/faccion Gremio | Dominar el puerto');
ok('jugador no puede editar el mundo directamente',!out.ok&&/modo Director/.test(out.message));
world.rpg.role='director';
ok('Director crea facción',E.executeCampaignCommand(world,'/faccion Gremio | Dominar el puerto').changed&&world.rpg.worldState.factions.length===1);
ok('Director crea y avanza reloj',E.executeCampaignCommand(world,'/reloj Alarma 0/6').changed&&E.executeCampaignCommand(world,'/reloj Alarma +2').changed&&world.rpg.worldState.clocks[0].value===2);
ok('Director registra misión',E.executeCampaignCommand(world,'/mision Encontrar la llave').changed&&world.rpg.worldState.quests[0].status==='active');
ok('Director gestiona inventario',E.executeCampaignCommand(world,'/inventario + Llave de cobre').changed&&world.rpg.worldState.inventory[0].name==='Llave de cobre');
ok('Director modifica relaciones',E.executeCampaignCommand(world,'/relacion Iria +3').changed&&world.rpg.worldState.relationships.Iria===3);
ok('Director registra pistas, heridas y rumores',E.executeCampaignCommand(world,'/pista + Sangre azul').changed&&E.executeCampaignCommand(world,'/herida + Costilla rota').changed&&E.executeCampaignCommand(world,'/rumor + El rey ha muerto').changed);
ok('Director actualiza tiempo',E.executeCampaignCommand(world,'/tiempo Noche del tercer día').changed&&world.rpg.worldState.clock==='Noche del tercer día');
ok('/ayuda enseña comandos a principiantes',/\/reloj/.test(E.executeCampaignCommand(world,'/ayuda').message));

const seed=makeSeed();const story=seed.stories[0];story.projectMode='rpg';story.outputLanguage='es';story.rpg={role:'player',experience:'beginner',mentorMode:true,player:{...E.defaultPlayer(),name:'Sol',occupation:'Explorador',motivation:'Encontrar el mapa',equipment:'Linterna',attributes:{strength:3,agility:3,resistance:3,control:3,flow:3,reserve:0},resources:{pemCurrent:100,hpCurrent:80}}};
seed.characters=[{id:'npc_iria',storyId:story.id,name:'Iria',role:'Guardia',description:'Prudente y leal',traits:['prudente'],knowledge:'Conoce la entrada, no el mapa',omniscient:false}];
seed.settings.ai.apiKey='sk-'+'x'.repeat(40);seed.settings.ai.verifiedAt=Date.now();
let calls=0;const bridge={aiGenerate:async p=>{calls++;return{ok:true,text:JSON.stringify({narracion:'La compuerta desciende y obliga a todos a reconsiderar la ruta.\n\n—La alarma ya empezó —dice Iria—. Si seguimos, el gremio sabrá dónde estamos.',pregunta:'¿Qué haces?',consecuencias:['La alarma del gremio avanza.'],mundo:{ubicacion:'Galería inferior',reloj:'Medianoche',hechos:['La compuerta está cerrada.']},conocimiento:[{personaje:'Iria',aprende:'Sol busca un mapa.'}],sistemas:{relojes:[{nombre:'Alarma',delta:1,max:6}],inventario:{agregar:['Sello roto'],retirar:[]},misiones:[{titulo:'Escapar de la galería',estado:'active'}],relaciones:[{personaje:'Iria',delta:1}],heridas:['Corte superficial'],pistas:['La runa apunta al norte'],facciones:[{nombre:'Gremio',progreso:5}]},mentor:'Los relojes muestran amenazas que avanzan aunque no ataques.'})}}};
const app=makeApp({seed,bridge});
setTimeout(async()=>{const w=app.w,d=w.document,probe=w.__probe,sid=probe('DATA.stories[0].id');probe(`openStoryEditor("${sid}")`);
  probe(`openSessionZero("${sid}")`);ok('sesión cero abre para principiantes',d.getElementById('sessionZeroBackdrop').classList.contains('active'));
  d.getElementById('szRole').value='director';d.getElementById('szExperience').value='beginner';d.getElementById('szWork').value='Fortaleza Infinita';d.getElementById('szAuthor').value='Creadora Ejemplo';d.getElementById('szEntry').value='El grupo despierta bajo una ciudad sellada.';d.getElementById('szTone').value='Misterio oscuro';d.getElementById('szDifficulty').value='challenging';d.getElementById('szLethality').value='dangerous';d.getElementById('szLimits').value='violencia gráfica';probe('saveSessionZero()');
  ok('sesión cero guarda rol, obra, riesgo y límites',probe('DATA.stories[0].rpg.role')==='director'&&probe('DATA.stories[0].rpg.campaign.referenceWork')==='Fortaleza Infinita'&&probe('DATA.stories[0].rpg.campaign.difficulty')==='challenging'&&probe('DATA.stories[0].rpg.campaign.limits[0]')==='violencia gráfica');
  d.getElementById('rpgWorldDashboardBtn').click();ok('Director abre panel de sistemas',d.getElementById('worldDashboardBackdrop').classList.contains('active')&&d.getElementById('worldToolForm').style.display==='grid');
  d.getElementById('worldToolType').value='factions';d.getElementById('worldToolName').value='Custodios';d.getElementById('worldToolDetail').value='Cerrar la ciudad';probe('addWorldTool()');ok('panel crea facción sin escribir JSON',probe('DATA.stories[0].rpg.worldState.factions[0].name')==='Custodios');
  d.getElementById('worldDashboardBackdrop').classList.remove('active');
  d.getElementById('rpgTurnInput').value='/estado';await probe('submitRpgTurn()');ok('comando local no consume llamada IA',calls===0&&/Misiones:/.test(d.getElementById('rpgTurnLog').textContent));
  d.getElementById('rpgRoleSelect').value='player';d.getElementById('rpgRoleSelect').dispatchEvent(new w.Event('change',{bubbles:true}));
  d.getElementById('rpgTurnInput').value='// intento abrir la compuerta CD 15';await probe('submitRpgTurn()');
  ok('acción de jugador sí llama al GM',calls===1);
  const state=probe('DATA.stories[0].rpg.worldState');
  ok('tool output actualiza reloj, inventario, misión y relación',state.clocks[0].value===1&&state.inventory[0].name==='Sello roto'&&state.quests[0].title==='Escapar de la galería'&&state.relationships.Iria===1);
  ok('tool output persiste herida, pista y facción',state.wounds.length===1&&state.clues.length===1&&state.factions.some(f=>f.name==='Gremio'&&f.progress===5));
  ok('Mentor enseña fuera de narración',/Mentor: Los relojes/.test(d.getElementById('rpgTurnLog').textContent));
  const prompt=app.w.__probe('buildRpgPrompt(DATA.stories[0], LoreRpgEngine.parseInput("// miro"), LoreRpgEngine.resolveAction(DATA.stories[0], LoreRpgEngine.parseInput("// miro"), {forcedRoll:10})).system');
  ok('prompt incluye rol, dificultad, sistemas y límites',/JUGADOR/.test(prompt)&&/challenging/.test(prompt)&&/violencia gráfica/.test(prompt)&&/inventario/.test(prompt));
  R.done();
},2500);
